[package]
name = "egui-gizmo-demo"
version = "0.1.0"
authors = ["Urho Laukkarinen <urho.laukkarinen@gmail.com>"]
edition = "2021"

license = "MIT"

[dependencies]
macroquad = "0.3.25"
egui = "0.21.0"
egui-macroquad = { git = "https://github.com/ziloka/egui-macroquad.git", rev = "81216f2b1978f3954e837c7d15c60c8a726708e0" }
egui-gizmo = { path = ".." }
