[package]
name = "egui-gizmo-demo"
version = "0.1.0"
authors = ["Urho Laukkarinen <urho.laukkarinen@gmail.com>"]
edition = "2021"

license = "MIT"

[dependencies]
macroquad = "0.3.25"
egui = "0.20.1"
egui-macroquad = { git = "https://github.com/matthiascy/egui-macroquad.git", rev = "069cbffb86c88b8bcf886fbf8eedbb4198a9fdc8" }
egui-gizmo = { path = ".." }
