[package]
name = "egui-gizmo-demo"
version = "0.1.0"
authors = ["Urho Laukkarinen <urho.laukkarinen@gmail.com>"]
edition = "2021"

license = "MIT"

[dependencies]
egui-macroquad = { git = "https://github.com/urholaukkarinen/egui-macroquad.git", rev = "16c753b" }
egui = "0.23.0"
egui-gizmo = { path = ".." }
macroquad = "0.3.25"
